# importing the packages

In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import sklearn
import warnings
warnings.filterwarnings('ignore')

# Load the data

In [41]:
df=pd.read_csv('./Iris.csv')

In [42]:
df.tail(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
140  Iris-virginica  
141  Iris-virginica  
142  Iris-virginica  
143  Iris-virginica  
144  Iris-virginica  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [43]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [44]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

# converting the values into categorical values to numerical values

In [71]:
df['Species']=df['Species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2})

# splitting the data into x and y and train_test 

In [72]:
x=df.drop(['Species'],axis=1)
y=df['Species']

In [73]:
x.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [74]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Species, dtype: int64

In [75]:
from sklearn.model_selection import train_test_split

In [76]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [77]:
x_train

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
96    97            5.7           2.9            4.2           1.3
105  106            7.6           3.0            6.6           2.1
66    67            5.6           3.0            4.5           1.5
0      1            5.1           3.5            1.4           0.2
122  123            7.7           2.8            6.7           2.0
..   ...            ...           ...            ...           ...
71    72            6.1           2.8            4.0           1.3
106  107            4.9           2.5            4.5           1.7
14    15            5.8           4.0            1.2           0.2
92    93            5.8           2.6            4.0           1.2
102  103            7.1           3.0            5.9           2.1

[100 rows x 5 columns]

# Fitting the data to the algo

In [78]:
from sklearn.naive_bayes import MultinomialNB

In [79]:
reg=MultinomialNB()

In [80]:
reg.fit(x_train,y_train)

MultinomialNB()

In [81]:
y_train_pred=reg.predict(x_train)

In [84]:
data=pd.DataFrame({'actual':y_train,"predict":y_train_pred})

In [85]:
data

actual  predict
96        1        2
105       2        1
66        1        1
0         0        0
122       2        2
..      ...      ...
71        1        1
106       2        2
14        0        0
92        1        2
102       2        1

[100 rows x 2 columns]

In [82]:
y_test_pred=reg.predict(x_test)

In [86]:
data1=pd.DataFrame({'actual':y_test,"predicted":y_test_pred})

In [87]:
data1

actual  predicted
73        1          1
18        0          0
118       2          2
78        1          1
76        1          1
31        0          0
64        1          1
141       2          2
68        1          1
82        1          1
110       2          2
12        0          0
36        0          0
9         0          0
19        0          0
56        1          1
104       2          1
69        1          1
55        1          1
132       2          2
29        0          0
127       2          2
26        0          0
128       2          2
131       2          2
145       2          2
108       2          2
143       2          2
45        0          1
30        0          0
22        0          0
15        0          0
65        1          1
11        0          0
42        0          1
146       2          2
51        1          1
27        0          0
4         0          0
32        0          0
142       2          2
85        1          1
86        1          1
16        0          0
10        0          0
81        1          1
133       2          2
137       2          2
75        1          1
109       2          1

# checking the validation report for the algorithm 

In [88]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [89]:
accuracy_score(y_train,y_train_pred)

0.82

In [90]:
confusion_matrix(y_train,y_train_pred)

array([[28,  3,  0],
       [ 0, 25, 10],
       [ 0,  5, 29]], dtype=int64)

In [91]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       1.00      0.90      0.95        31
           1       0.76      0.71      0.74        35
           2       0.74      0.85      0.79        34

    accuracy                           0.82       100
   macro avg       0.83      0.82      0.83       100
weighted avg       0.83      0.82      0.82       100



In [92]:
##for the test data

In [93]:
accuracy_score(y_test,y_test_pred)

0.92

In [94]:
confusion_matrix(y_test,y_test_pred)

array([[17,  2,  0],
       [ 0, 15,  0],
       [ 0,  2, 14]], dtype=int64)

In [95]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       1.00      0.89      0.94        19
           1       0.79      1.00      0.88        15
           2       1.00      0.88      0.93        16

    accuracy                           0.92        50
   macro avg       0.93      0.92      0.92        50
weighted avg       0.94      0.92      0.92        50



# checking with the real data

In [96]:
c=[]
for i in x_test.iloc[0]:
    c.append(i)

In [97]:
reg.predict([c])

array([1], dtype=int64)

In [99]:
sol=reg.predict([c])
sol=sol[0]
if sol==0:
    print('setosa')
elif sol==1:
    print('versi_color')
else:
    print('verginica')
    

versi_color
